### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by M0nica** [M0nica/React-Ladies#1]
Add this Favicon to the `home-v1` branch
 https://github.com/M0nica/React-Ladies/blob/master/favicon.ico

**Comment by M0nica** [comment]
**Please contribute to the `home-v1` branch.**

**Comment by soulspark666** [comment]
Please specify the location of where to add it.

**Comment by Anshulgangwar63** [comment]
Is it still open?

**Comment by M0nica** [comment]
Yes, this is still open @Anshulgangwar63!

**Comment by ramkrishn123** [comment]
Okay the work will be done on time.
