### ISSUE TITLE
Add .gitignore to project and add unwanted files/directories

### ISSUE THREAD

**Issue by mahewi** [M0nica/React-Ladies#11]
I noticed that the project (branch home-v1) doesn't contain a .gitignore file which is really useful because files/directories such as node_modules/ & .DS_Store should not be included in version control. They take up space and should be automatically generated by running 'npm install' command locally / in build phase.

**Comment by M0nica** [comment]
Thanks @mahewi. Are you interested in implementing this?

**Comment by mahewi** [comment]
Yes, I can implement this :)
