### ISSUE TITLE
Fix /NYC page

### ISSUE THREAD

**Issue by M0nica** [M0nica/React-Ladies#2]
The `/NYC` page should display what's currently in the `/nyc/index.html` (an embedded form). Currently, this page renders as a blank page instead of displaying the proper JSX/HTML.

For reference, it should appear similar to this: http://www.reactladies.com/nyc/ but maybe with the sitewide header/footer. Please contribute to the home-v1 branch.

**Comment by M0nica** [comment]
**Please contribute to the `home-v1` branch.**

**Comment by Anshulgangwar63** [comment]
I would like to work on this issue

**Comment by Anshulgangwar63** [comment]
@M0nica Sorry to bother you again but your /nyc/index.html contains only 18 lines of code and contains only a link to js file and an iframe tag. I am a beginner and it's my first issue so can you please me out.

**Comment by M0nica** [comment]
@Anshulgangwar63 yes that's the right file -- currently instead of displaying those 18 lines trying to navigate to that page results in a blank page. I want the iframe on that page to render when someone visits that page.
