### ISSUE TITLE
Add website title

### ISSUE THREAD

**Issue by M0nica** [M0nica/React-Ladies#4]
Add website title "React Ladies" 

HTML titles

> defines a title in the browser tab
> provides a title for the page when it is added to favorites
> displays a title for the page in search engine results

**Comment by rajcrk** [comment]
I`m gonna work on it

**Comment by AngelsProjects** [comment]
I can take this one

**Comment by ryan4664** [comment]
I already see this in the repo?  I don't see the issue.
